# Generated by Django 5.1.1 on 2024-09-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('Libre', 'Libre'), ('Reservada', 'Reservada'), ('Cancelada', 'Cancelada')], default='Libre', max_length=15),
        ),
    ]
