# Generated by Django 5.1.1 on 2024-09-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_reserva_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
